"""empty message

Revision ID: c3a4b4794f06
Revises: 
Create Date: 2023-04-06 03:19:46.147777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3a4b4794f06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_name', sa.String(length=200), nullable=True))
    op.drop_column('products', 'productname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('productname', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('products', 'product_name')
    # ### end Alembic commands ###
